
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v1
      with:
        host: ftp4a.seatgeekenterprise.co.uk:42121/
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: "UserContent"